# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Yoadmin/Documents/vivado/RV32I/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_system_ila_0_1/microcontroler_tb_system_ila_0_1.xci
# IP: The module: 'microcontroler_tb_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Yoadmin/Documents/vivado/RV32I/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_system_ila_0_1/bd_0/bd_f4cf.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f4cf || ORIG_REF_NAME==bd_f4cf} -quiet] -quiet

# IP: c:/Users/Yoadmin/Documents/vivado/RV32I/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_system_ila_0_1/bd_0/ip/ip_0/bd_f4cf_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f4cf_ila_lib_0 || ORIG_REF_NAME==bd_f4cf_ila_lib_0} -quiet] -quiet

# XDC: c:/Users/Yoadmin/Documents/vivado/RV32I/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_system_ila_0_1/microcontroler_tb_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microcontroler_tb_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Yoadmin/Documents/vivado/RV32I/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f4cf_ila_lib_0 || ORIG_REF_NAME==bd_f4cf_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Yoadmin/Documents/vivado/RV32I/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f4cf_ila_lib_0 || ORIG_REF_NAME==bd_f4cf_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Yoadmin/Documents/vivado/RV32I/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_system_ila_0_1/bd_0/ip/ip_0/bd_f4cf_ila_lib_0_ooc.xdc

# XDC: c:/Users/Yoadmin/Documents/vivado/RV32I/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_system_ila_0_1/bd_0/bd_f4cf_ooc.xdc

# IP: C:/Users/Yoadmin/Documents/vivado/RV32I/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_system_ila_0_1/microcontroler_tb_system_ila_0_1.xci
# IP: The module: 'microcontroler_tb_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Yoadmin/Documents/vivado/RV32I/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_system_ila_0_1/bd_0/bd_f4cf.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f4cf || ORIG_REF_NAME==bd_f4cf} -quiet] -quiet

# IP: c:/Users/Yoadmin/Documents/vivado/RV32I/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_system_ila_0_1/bd_0/ip/ip_0/bd_f4cf_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f4cf_ila_lib_0 || ORIG_REF_NAME==bd_f4cf_ila_lib_0} -quiet] -quiet

# XDC: c:/Users/Yoadmin/Documents/vivado/RV32I/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_system_ila_0_1/microcontroler_tb_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microcontroler_tb_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Yoadmin/Documents/vivado/RV32I/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f4cf_ila_lib_0 || ORIG_REF_NAME==bd_f4cf_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Yoadmin/Documents/vivado/RV32I/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f4cf_ila_lib_0 || ORIG_REF_NAME==bd_f4cf_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Yoadmin/Documents/vivado/RV32I/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_system_ila_0_1/bd_0/ip/ip_0/bd_f4cf_ila_lib_0_ooc.xdc

# XDC: c:/Users/Yoadmin/Documents/vivado/RV32I/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_system_ila_0_1/bd_0/bd_f4cf_ooc.xdc
