# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pinout.xdc

# Block Designs: bd/microcontroler_tb/microcontroler_tb.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microcontroler_tb || ORIG_REF_NAME==microcontroler_tb} -quiet] -quiet

# IP: bd/microcontroler_tb/ip/microcontroler_tb_uCtb_0_0/microcontroler_tb_uCtb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microcontroler_tb_uCtb_0_0 || ORIG_REF_NAME==microcontroler_tb_uCtb_0_0} -quiet] -quiet

# IP: bd/microcontroler_tb/ip/microcontroler_tb_axi_cdma_0_0/microcontroler_tb_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microcontroler_tb_axi_cdma_0_0 || ORIG_REF_NAME==microcontroler_tb_axi_cdma_0_0} -quiet] -quiet

# IP: bd/microcontroler_tb/ip/microcontroler_tb_processing_system7_0_0/microcontroler_tb_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microcontroler_tb_processing_system7_0_0 || ORIG_REF_NAME==microcontroler_tb_processing_system7_0_0} -quiet] -quiet

# IP: bd/microcontroler_tb/ip/microcontroler_tb_axi_bram_ctrl_0_0/microcontroler_tb_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microcontroler_tb_axi_bram_ctrl_0_0 || ORIG_REF_NAME==microcontroler_tb_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/microcontroler_tb/ip/microcontroler_tb_axi_bram_ctrl_0_1/microcontroler_tb_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microcontroler_tb_axi_bram_ctrl_0_1 || ORIG_REF_NAME==microcontroler_tb_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/microcontroler_tb/ip/microcontroler_tb_rst_ps7_0_50M_0/microcontroler_tb_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microcontroler_tb_rst_ps7_0_50M_0 || ORIG_REF_NAME==microcontroler_tb_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/microcontroler_tb/ip/microcontroler_tb_axi_bram_ctrl_Instr_bram_0/microcontroler_tb_axi_bram_ctrl_Instr_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microcontroler_tb_axi_bram_ctrl_Instr_bram_0 || ORIG_REF_NAME==microcontroler_tb_axi_bram_ctrl_Instr_bram_0} -quiet] -quiet

# IP: bd/microcontroler_tb/ip/microcontroler_tb_axi_bram_ctrl_Instr_bram_1/microcontroler_tb_axi_bram_ctrl_Instr_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microcontroler_tb_axi_bram_ctrl_Instr_bram_1 || ORIG_REF_NAME==microcontroler_tb_axi_bram_ctrl_Instr_bram_1} -quiet] -quiet

# IP: bd/microcontroler_tb/ip/microcontroler_tb_xlconcat_0_0/microcontroler_tb_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microcontroler_tb_xlconcat_0_0 || ORIG_REF_NAME==microcontroler_tb_xlconcat_0_0} -quiet] -quiet

# IP: bd/microcontroler_tb/ip/microcontroler_tb_xlconcat_0_1/microcontroler_tb_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microcontroler_tb_xlconcat_0_1 || ORIG_REF_NAME==microcontroler_tb_xlconcat_0_1} -quiet] -quiet

# IP: bd/microcontroler_tb/ip/microcontroler_tb_xlslice_0_0/microcontroler_tb_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microcontroler_tb_xlslice_0_0 || ORIG_REF_NAME==microcontroler_tb_xlslice_0_0} -quiet] -quiet

# IP: bd/microcontroler_tb/ip/microcontroler_tb_ps7_0_axi_periph_1/microcontroler_tb_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microcontroler_tb_ps7_0_axi_periph_1 || ORIG_REF_NAME==microcontroler_tb_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/microcontroler_tb_axi_smc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microcontroler_tb_axi_smc_1 || ORIG_REF_NAME==microcontroler_tb_axi_smc_1} -quiet] -quiet

# IP: bd/microcontroler_tb/ip/microcontroler_tb_system_ila_0_1/microcontroler_tb_system_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microcontroler_tb_system_ila_0_1 || ORIG_REF_NAME==microcontroler_tb_system_ila_0_1} -quiet] -quiet

# IP: bd/microcontroler_tb/ip/microcontroler_tb_auto_pc_0/microcontroler_tb_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microcontroler_tb_auto_pc_0 || ORIG_REF_NAME==microcontroler_tb_auto_pc_0} -quiet] -quiet

# XDC: bd/microcontroler_tb/microcontroler_tb_ooc.xdc
