# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths c:/Users/Yoadmin/Documents/vivado/ip_repo/Axi4Slave_1.0 [current_project]
update_ip_catalog
set_property ip_output_repo {c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {{C:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/hdl/microcontroler_tb_wrapper.vhd}}
add_files {{C:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/microcontroler_tb.bd}}
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_cdma_0_0/microcontroler_tb_axi_cdma_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_cdma_0_0/microcontroler_tb_axi_cdma_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_processing_system7_0_0/microcontroler_tb_processing_system7_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_bram_ctrl_0_0/microcontroler_tb_axi_bram_ctrl_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_bram_ctrl_0_1/microcontroler_tb_axi_bram_ctrl_0_1_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_rst_ps7_0_50M_0/microcontroler_tb_rst_ps7_0_50M_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_rst_ps7_0_50M_0/microcontroler_tb_rst_ps7_0_50M_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_rst_ps7_0_50M_0/microcontroler_tb_rst_ps7_0_50M_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_bram_ctrl_Instr_bram_0/microcontroler_tb_axi_bram_ctrl_Instr_bram_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_bram_ctrl_Instr_bram_1/microcontroler_tb_axi_bram_ctrl_Instr_bram_1_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_1/bd_75b1_psr_aclk_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_1/bd_75b1_psr_aclk_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_2/bd_75b1_arsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_3/bd_75b1_rsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_4/bd_75b1_awsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_5/bd_75b1_wsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_6/bd_75b1_bsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_10/bd_75b1_s00a2s_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_11/bd_75b1_sarn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_12/bd_75b1_srn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_13/bd_75b1_sawn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_14/bd_75b1_swn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_15/bd_75b1_sbn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_16/bd_75b1_m00s2a_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_17/bd_75b1_m00arn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_18/bd_75b1_m00rn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_19/bd_75b1_m00awn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_20/bd_75b1_m00wn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_21/bd_75b1_m00bn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_23/bd_75b1_m01s2a_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_24/bd_75b1_m01arn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_25/bd_75b1_m01rn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_26/bd_75b1_m01awn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_27/bd_75b1_m01wn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_28/bd_75b1_m01bn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_30/bd_75b1_m02s2a_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_31/bd_75b1_m02arn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_32/bd_75b1_m02rn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_33/bd_75b1_m02awn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_34/bd_75b1_m02wn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_smc_1/bd_0/ip/ip_35/bd_75b1_m02bn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_system_ila_0_1/microcontroler_tb_system_ila_0_1_ooc.xdc}}]
set_property used_in_synthesis false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_system_ila_0_1/bd_0/ip/ip_0/bd_f4cf_ila_lib_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_system_ila_0_1/bd_0/bd_f4cf_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_auto_pc_0/microcontroler_tb_auto_pc_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{C:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/sources_1/bd/microcontroler_tb/microcontroler_tb_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/constrs_1/new/pinout.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Yoadmin/Documents/git/RV32I/Synthetizable/Vivado project/RV32I.srcs/constrs_1/new/pinout.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top microcontroler_tb_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef microcontroler_tb_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file microcontroler_tb_wrapper_utilization_synth.rpt -pb microcontroler_tb_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
