# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Yoadmin/Documents/vivado/RV32I/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_bram_ctrl_0_1/microcontroler_tb_axi_bram_ctrl_0_1.xci
# IP: The module: 'microcontroler_tb_axi_bram_ctrl_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Yoadmin/Documents/vivado/RV32I/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_bram_ctrl_0_1/microcontroler_tb_axi_bram_ctrl_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microcontroler_tb_axi_bram_ctrl_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Yoadmin/Documents/vivado/RV32I/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_bram_ctrl_0_1/microcontroler_tb_axi_bram_ctrl_0_1.xci
# IP: The module: 'microcontroler_tb_axi_bram_ctrl_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Yoadmin/Documents/vivado/RV32I/RV32I.srcs/sources_1/bd/microcontroler_tb/ip/microcontroler_tb_axi_bram_ctrl_0_1/microcontroler_tb_axi_bram_ctrl_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microcontroler_tb_axi_bram_ctrl_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
