/* Generated by Yosys 0.9+3624 (git sha1 UNKNOWN, clang 7.0.1-8+deb10u2 -fPIC -Os) */

module ControlUnit(Z, Trap, CondTrue, OPCODE, FUNCT3, FUNCT7, PC_Sel, A_Sel, B_Sel, WB_Sel, Imm_Sel, ALU_Sel, RegFile_Wen, DMem_Wen, CSRFile_Wen, CSRFile_Trap_Wen, MRet, ECall, EBreak, Ill_op);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire [1:0] _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire [3:0] _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire [1:0] _18_;
  wire [1:0] _19_;
  wire [3:0] _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire [3:0] _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire [1:0] _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire [1:0] _47_;
  wire [1:0] _48_;
  wire [1:0] _49_;
  wire [1:0] _50_;
  wire [2:0] _51_;
  wire [3:0] _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _60_;
  wire _61_;
  wire [1:0] _62_;
  wire _63_;
  wire _64_;
  wire _65_;
  wire _66_;
  wire _67_;
  wire _68_;
  wire _69_;
  wire _70_;
  wire _71_;
  wire _72_;
  wire _73_;
  output [3:0] ALU_Sel;
  output [1:0] A_Sel;
  output [1:0] B_Sel;
  output CSRFile_Trap_Wen;
  output CSRFile_Wen;
  input CondTrue;
  output DMem_Wen;
  output EBreak;
  output ECall;
  input [2:0] FUNCT3;
  input [3:0] FUNCT7;
  output Ill_op;
  output [2:0] Imm_Sel;
  output MRet;
  input [6:0] OPCODE;
  output [1:0] PC_Sel;
  output RegFile_Wen;
  input Trap;
  output [1:0] WB_Sel;
  input Z;
  wire \control.takebranch ;
  assign _20_ = 4'hc | { 2'h0, FUNCT3[2], 1'h0 };
  assign _21_ = FUNCT3[1:0] == 2'h1;
  assign _23_ = FUNCT3[1:0] == 2'h2;
  assign _24_ = FUNCT3[1:0] == 2'h3;
  function [3:0] \112 ;
    input [3:0] a;
    input [11:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \112  = b[3:0];
      3'b?1?:
        \112  = b[7:4];
      3'b1??:
        \112  = b[11:8];
      default:
        \112  = a;
    endcase
  endfunction
  assign _25_ = \112 (4'hx, { 8'hf6, _20_ }, { _24_, _23_, _21_ });
  assign _26_ = _22_ == 1'h1;
  assign _27_ = FUNCT7[2:0] == 3'h0;
  assign _28_ = FUNCT7[2:0] == 3'h1;
  assign _29_ = FUNCT7[2:0] == 3'h6;
  function [0:0] \125 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \125  = b[0:0];
      3'b?1?:
        \125  = b[1:1];
      3'b1??:
        \125  = b[2:2];
      default:
        \125  = a;
    endcase
  endfunction
  assign _30_ = \125 (1'h1, 3'h3, { _29_, _28_, _27_ });
  function [0:0] \129 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \129  = b[0:0];
      3'b?1?:
        \129  = b[1:1];
      3'b1??:
        \129  = b[2:2];
      default:
        \129  = a;
    endcase
  endfunction
  assign _31_ = \129 (1'h0, 3'h4, { _29_, _28_, _27_ });
  function [0:0] \133 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \133  = b[0:0];
      3'b?1?:
        \133  = b[1:1];
      3'b1??:
        \133  = b[2:2];
      default:
        \133  = a;
    endcase
  endfunction
  assign _32_ = \133 (1'h0, 3'h1, { _29_, _28_, _27_ });
  function [0:0] \137 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \137  = b[0:0];
      3'b?1?:
        \137  = b[1:1];
      3'b1??:
        \137  = b[2:2];
      default:
        \137  = a;
    endcase
  endfunction
  assign _34_ = \137 (1'h0, 3'h2, { _29_, _28_, _27_ });
  function [0:0] \141 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \141  = b[0:0];
      3'b?1?:
        \141  = b[1:1];
      3'b1??:
        \141  = b[2:2];
      default:
        \141  = a;
    endcase
  endfunction
  assign _35_ = \141 (1'h1, 3'h0, { _29_, _28_, _27_ });
  assign _36_ = _22_ == 1'h0;
  function [1:0] \148 ;
    input [1:0] a;
    input [3:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \148  = b[1:0];
      2'b1?:
        \148  = b[3:2];
      default:
        \148  = a;
    endcase
  endfunction
  assign _37_ = \148 (_62_, 4'hc, { _36_, _26_ });
  function [0:0] \151 ;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \151  = b[0:0];
      2'b1?:
        \151  = b[1:1];
      default:
        \151  = a;
    endcase
  endfunction
  assign _38_ = \151 (_63_, 2'h1, { _36_, _26_ });
  function [0:0] \154 ;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \154  = b[0:0];
      2'b1?:
        \154  = b[1:1];
      default:
        \154  = a;
    endcase
  endfunction
  assign _39_ = \154 (_66_, 2'h1, { _36_, _26_ });
  function [0:0] \156 ;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \156  = b[0:0];
      2'b1?:
        \156  = b[1:1];
      default:
        \156  = a;
    endcase
  endfunction
  assign _40_ = \156 (_67_, { _30_, 1'h0 }, { _36_, _26_ });
  function [0:0] \158 ;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \158  = b[0:0];
      2'b1?:
        \158  = b[1:1];
      default:
        \158  = a;
    endcase
  endfunction
  assign _41_ = \158 (_68_, { _31_, 1'h0 }, { _36_, _26_ });
  function [0:0] \160 ;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \160  = b[0:0];
      2'b1?:
        \160  = b[1:1];
      default:
        \160  = a;
    endcase
  endfunction
  assign _42_ = \160 (_69_, { _32_, 1'hx }, { _36_, _26_ });
  function [0:0] \162 ;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \162  = b[0:0];
      2'b1?:
        \162  = b[1:1];
      default:
        \162  = a;
    endcase
  endfunction
  assign _43_ = \162 (_70_, { _34_, 1'hx }, { _36_, _26_ });
  function [0:0] \164 ;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \164  = b[0:0];
      2'b1?:
        \164  = b[1:1];
      default:
        \164  = a;
    endcase
  endfunction
  assign _45_ = \164 (_71_, { _35_, 1'hx }, { _36_, _26_ });
  assign _46_ = OPCODE == 7'h73;
  function [1:0] \178 ;
    input [1:0] a;
    input [21:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \178  = b[1:0];
      11'b?????????1?:
        \178  = b[3:2];
      11'b????????1??:
        \178  = b[5:4];
      11'b???????1???:
        \178  = b[7:6];
      11'b??????1????:
        \178  = b[9:8];
      11'b?????1?????:
        \178  = b[11:10];
      11'b????1??????:
        \178  = b[13:12];
      11'b???1???????:
        \178  = b[15:14];
      11'b??1????????:
        \178  = b[17:16];
      11'b?1?????????:
        \178  = b[19:18];
      11'b1??????????:
        \178  = b[21:20];
      default:
        \178  = a;
    endcase
  endfunction
  assign _47_ = \178 (2'h3, { _37_, 10'h000, _08_, 8'h90 }, { _46_, _17_, _16_, _15_, _12_, _10_, _09_, _65_, _55_, _44_, _33_ });
  function [1:0] \190 ;
    input [1:0] a;
    input [21:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \190  = b[1:0];
      11'b?????????1?:
        \190  = b[3:2];
      11'b????????1??:
        \190  = b[5:4];
      11'b???????1???:
        \190  = b[7:6];
      11'b??????1????:
        \190  = b[9:8];
      11'b?????1?????:
        \190  = b[11:10];
      11'b????1??????:
        \190  = b[13:12];
      11'b???1???????:
        \190  = b[15:14];
      11'b??1????????:
        \190  = b[17:16];
      11'b?1?????????:
        \190  = b[19:18];
      11'b1??????????:
        \190  = b[21:20];
      default:
        \190  = a;
    endcase
  endfunction
  assign _48_ = \190 (2'hx, { _18_, 20'bxx000000000000xx01xx }, { _46_, _17_, _16_, _15_, _12_, _10_, _09_, _65_, _55_, _44_, _33_ });
  function [1:0] \202 ;
    input [1:0] a;
    input [21:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \202  = b[1:0];
      11'b?????????1?:
        \202  = b[3:2];
      11'b????????1??:
        \202  = b[5:4];
      11'b???????1???:
        \202  = b[7:6];
      11'b??????1????:
        \202  = b[9:8];
      11'b?????1?????:
        \202  = b[11:10];
      11'b????1??????:
        \202  = b[13:12];
      11'b???1???????:
        \202  = b[15:14];
      11'b??1????????:
        \202  = b[17:16];
      11'b?1?????????:
        \202  = b[19:18];
      11'b1??????????:
        \202  = b[21:20];
      default:
        \202  = a;
    endcase
  endfunction
  assign _49_ = \202 (2'hx, { _19_, 20'bxx000101010001xx0101 }, { _46_, _17_, _16_, _15_, _12_, _10_, _09_, _65_, _55_, _44_, _33_ });
  function [1:0] \215 ;
    input [1:0] a;
    input [21:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \215  = b[1:0];
      11'b?????????1?:
        \215  = b[3:2];
      11'b????????1??:
        \215  = b[5:4];
      11'b???????1???:
        \215  = b[7:6];
      11'b??????1????:
        \215  = b[9:8];
      11'b?????1?????:
        \215  = b[11:10];
      11'b????1??????:
        \215  = b[13:12];
      11'b???1???????:
        \215  = b[15:14];
      11'b??1????????:
        \215  = b[17:16];
      11'b?1?????????:
        \215  = b[19:18];
      11'b1??????????:
        \215  = b[21:20];
      default:
        \215  = a;
    endcase
  endfunction
  assign _50_ = \215 (2'hx, 22'b11xx0000xx01xx10100000, { _46_, _17_, _16_, _15_, _12_, _10_, _09_, _65_, _55_, _44_, _33_ });
  function [2:0] \228 ;
    input [2:0] a;
    input [32:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \228  = b[2:0];
      11'b?????????1?:
        \228  = b[5:3];
      11'b????????1??:
        \228  = b[8:6];
      11'b???????1???:
        \228  = b[11:9];
      11'b??????1????:
        \228  = b[14:12];
      11'b?????1?????:
        \228  = b[17:15];
      11'b????1??????:
        \228  = b[20:18];
      11'b???1???????:
        \228  = b[23:21];
      11'b??1????????:
        \228  = b[26:24];
      11'b?1?????????:
        \228  = b[29:27];
      11'b1??????????:
        \228  = b[32:30];
      default:
        \228  = a;
    endcase
  endfunction
  assign _51_ = \228 (3'hx, 33'b101xxxxxx000001000010000100011011, { _46_, _17_, _16_, _15_, _12_, _10_, _09_, _65_, _55_, _44_, _33_ });
  function [3:0] \237 ;
    input [3:0] a;
    input [43:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \237  = b[3:0];
      11'b?????????1?:
        \237  = b[7:4];
      11'b????????1??:
        \237  = b[11:8];
      11'b???????1???:
        \237  = b[15:12];
      11'b??????1????:
        \237  = b[19:16];
      11'b?????1?????:
        \237  = b[23:20];
      11'b????1??????:
        \237  = b[27:24];
      11'b???1???????:
        \237  = b[31:28];
      11'b??1????????:
        \237  = b[35:32];
      11'b?1?????????:
        \237  = b[39:36];
      11'b1??????????:
        \237  = b[43:40];
      default:
        \237  = a;
    endcase
  endfunction
  assign _52_ = \237 (4'hx, { _25_, 4'hx, FUNCT7[3], FUNCT3, _14_, 10'h002, FUNCT3[2:1], 16'h0x0e }, { _46_, _17_, _16_, _15_, _12_, _10_, _09_, _65_, _55_, _44_, _33_ });
  function [0:0] \249 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \249  = b[0:0];
      11'b?????????1?:
        \249  = b[1:1];
      11'b????????1??:
        \249  = b[2:2];
      11'b???????1???:
        \249  = b[3:3];
      11'b??????1????:
        \249  = b[4:4];
      11'b?????1?????:
        \249  = b[5:5];
      11'b????1??????:
        \249  = b[6:6];
      11'b???1???????:
        \249  = b[7:7];
      11'b??1????????:
        \249  = b[8:8];
      11'b?1?????????:
        \249  = b[9:9];
      11'b1??????????:
        \249  = b[10:10];
      default:
        \249  = a;
    endcase
  endfunction
  assign _53_ = \249 (1'h0, { _38_, 10'h1af }, { _46_, _17_, _16_, _15_, _12_, _10_, _09_, _65_, _55_, _44_, _33_ });
  assign _00_ = 1'h0 | FUNCT3[2];
  function [0:0] \262 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \262  = b[0:0];
      11'b?????????1?:
        \262  = b[1:1];
      11'b????????1??:
        \262  = b[2:2];
      11'b???????1???:
        \262  = b[3:3];
      11'b??????1????:
        \262  = b[4:4];
      11'b?????1?????:
        \262  = b[5:5];
      11'b????1??????:
        \262  = b[6:6];
      11'b???1???????:
        \262  = b[7:7];
      11'b??1????????:
        \262  = b[8:8];
      11'b?1?????????:
        \262  = b[9:9];
      11'b1??????????:
        \262  = b[10:10];
      default:
        \262  = a;
    endcase
  endfunction
  assign _54_ = \262 (1'h0, 11'h040, { _46_, _17_, _16_, _15_, _12_, _10_, _09_, _65_, _55_, _44_, _33_ });
  function [0:0] \274 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \274  = b[0:0];
      11'b?????????1?:
        \274  = b[1:1];
      11'b????????1??:
        \274  = b[2:2];
      11'b???????1???:
        \274  = b[3:3];
      11'b??????1????:
        \274  = b[4:4];
      11'b?????1?????:
        \274  = b[5:5];
      11'b????1??????:
        \274  = b[6:6];
      11'b???1???????:
        \274  = b[7:7];
      11'b??1????????:
        \274  = b[8:8];
      11'b?1?????????:
        \274  = b[9:9];
      11'b1??????????:
        \274  = b[10:10];
      default:
        \274  = a;
    endcase
  endfunction
  assign _56_ = \274 (1'h0, { _39_, 10'h000 }, { _46_, _17_, _16_, _15_, _12_, _10_, _09_, _65_, _55_, _44_, _33_ });
  function [0:0] \286 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \286  = b[0:0];
      11'b?????????1?:
        \286  = b[1:1];
      11'b????????1??:
        \286  = b[2:2];
      11'b???????1???:
        \286  = b[3:3];
      11'b??????1????:
        \286  = b[4:4];
      11'b?????1?????:
        \286  = b[5:5];
      11'b????1??????:
        \286  = b[6:6];
      11'b???1???????:
        \286  = b[7:7];
      11'b??1????????:
        \286  = b[8:8];
      11'b?1?????????:
        \286  = b[9:9];
      11'b1??????????:
        \286  = b[10:10];
      default:
        \286  = a;
    endcase
  endfunction
  assign _57_ = \286 (1'h1, { _40_, 10'h000 }, { _46_, _17_, _16_, _15_, _12_, _10_, _09_, _65_, _55_, _44_, _33_ });
  assign _11_ = _00_ | FUNCT3[1];
  function [0:0] \298 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \298  = b[0:0];
      11'b?????????1?:
        \298  = b[1:1];
      11'b????????1??:
        \298  = b[2:2];
      11'b???????1???:
        \298  = b[3:3];
      11'b??????1????:
        \298  = b[4:4];
      11'b?????1?????:
        \298  = b[5:5];
      11'b????1??????:
        \298  = b[6:6];
      11'b???1???????:
        \298  = b[7:7];
      11'b??1????????:
        \298  = b[8:8];
      11'b?1?????????:
        \298  = b[9:9];
      11'b1??????????:
        \298  = b[10:10];
      default:
        \298  = a;
    endcase
  endfunction
  assign _58_ = \298 (1'h0, { _41_, 10'h000 }, { _46_, _17_, _16_, _15_, _12_, _10_, _09_, _65_, _55_, _44_, _33_ });
  assign _22_ = _11_ | FUNCT3[0];
  function [0:0] \310 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \310  = b[0:0];
      11'b?????????1?:
        \310  = b[1:1];
      11'b????????1??:
        \310  = b[2:2];
      11'b???????1???:
        \310  = b[3:3];
      11'b??????1????:
        \310  = b[4:4];
      11'b?????1?????:
        \310  = b[5:5];
      11'b????1??????:
        \310  = b[6:6];
      11'b???1???????:
        \310  = b[7:7];
      11'b??1????????:
        \310  = b[8:8];
      11'b?1?????????:
        \310  = b[9:9];
      11'b1??????????:
        \310  = b[10:10];
      default:
        \310  = a;
    endcase
  endfunction
  assign _59_ = \310 (1'h0, { _42_, 10'hxxx }, { _46_, _17_, _16_, _15_, _12_, _10_, _09_, _65_, _55_, _44_, _33_ });
  function [0:0] \322 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \322  = b[0:0];
      11'b?????????1?:
        \322  = b[1:1];
      11'b????????1??:
        \322  = b[2:2];
      11'b???????1???:
        \322  = b[3:3];
      11'b??????1????:
        \322  = b[4:4];
      11'b?????1?????:
        \322  = b[5:5];
      11'b????1??????:
        \322  = b[6:6];
      11'b???1???????:
        \322  = b[7:7];
      11'b??1????????:
        \322  = b[8:8];
      11'b?1?????????:
        \322  = b[9:9];
      11'b1??????????:
        \322  = b[10:10];
      default:
        \322  = a;
    endcase
  endfunction
  assign _60_ = \322 (1'h0, { _43_, 10'hxxx }, { _46_, _17_, _16_, _15_, _12_, _10_, _09_, _65_, _55_, _44_, _33_ });
  assign _33_ = OPCODE == 7'h37;
  function [0:0] \334 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \334  = b[0:0];
      11'b?????????1?:
        \334  = b[1:1];
      11'b????????1??:
        \334  = b[2:2];
      11'b???????1???:
        \334  = b[3:3];
      11'b??????1????:
        \334  = b[4:4];
      11'b?????1?????:
        \334  = b[5:5];
      11'b????1??????:
        \334  = b[6:6];
      11'b???1???????:
        \334  = b[7:7];
      11'b??1????????:
        \334  = b[8:8];
      11'b?1?????????:
        \334  = b[9:9];
      11'b1??????????:
        \334  = b[10:10];
      default:
        \334  = a;
    endcase
  endfunction
  assign _61_ = \334 (1'h1, { _45_, 10'hxxx }, { _46_, _17_, _16_, _15_, _12_, _10_, _09_, _65_, _55_, _44_, _33_ });
  function [0:0] \335 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \335  = b[0:0];
      11'b?????????1?:
        \335  = b[1:1];
      11'b????????1??:
        \335  = b[2:2];
      11'b???????1???:
        \335  = b[3:3];
      11'b??????1????:
        \335  = b[4:4];
      11'b?????1?????:
        \335  = b[5:5];
      11'b????1??????:
        \335  = b[6:6];
      11'b???1???????:
        \335  = b[7:7];
      11'b??1????????:
        \335  = b[8:8];
      11'b?1?????????:
        \335  = b[9:9];
      11'b1??????????:
        \335  = b[10:10];
      default:
        \335  = a;
    endcase
  endfunction
  assign \control.takebranch  = \335 (\control.takebranch , { \control.takebranch , \control.takebranch , \control.takebranch , \control.takebranch , \control.takebranch , \control.takebranch , _05_, \control.takebranch , \control.takebranch , \control.takebranch , \control.takebranch  }, { _46_, _17_, _16_, _15_, _12_, _10_, _09_, _65_, _55_, _44_, _33_ });
  assign _62_ = Trap ? 2'h3 : _47_;
  assign _63_ = Trap ? 1'h0 : _53_;
  assign _64_ = Trap ? 1'h0 : _54_;
  assign _66_ = Trap ? 1'h0 : _56_;
  assign _67_ = Trap ? 1'h1 : _57_;
  assign _68_ = Trap ? 1'h0 : _58_;
  assign _44_ = OPCODE == 7'h17;
  assign _69_ = Trap ? 1'h0 : _59_;
  assign _70_ = Trap ? 1'h0 : _60_;
  assign _71_ = Trap ? 1'h0 : _61_;
  assign _55_ = OPCODE == 7'h6f;
  assign _65_ = OPCODE == 7'h67;
  assign _72_ = { FUNCT3[2], FUNCT3[0] } == 2'h0;
  assign _73_ = ~ Z;
  assign _01_ = { FUNCT3[2], FUNCT3[0] } == 2'h1;
  assign _02_ = { FUNCT3[2], FUNCT3[0] } == 2'h2;
  assign _03_ = ~ CondTrue;
  assign _04_ = { FUNCT3[2], FUNCT3[0] } == 2'h3;
  function [0:0] \57 ;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \57  = b[0:0];
      4'b??1?:
        \57  = b[1:1];
      4'b?1??:
        \57  = b[2:2];
      4'b1???:
        \57  = b[3:3];
      default:
        \57  = a;
    endcase
  endfunction
  assign _05_ = \57 (\control.takebranch , { _03_, CondTrue, _73_, Z }, { _04_, _02_, _01_, _72_ });
  assign _06_ = _05_ == 1'h1;
  assign _07_ = _05_ == 1'h0;
  function [1:0] \65 ;
    input [1:0] a;
    input [3:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \65  = b[1:0];
      2'b1?:
        \65  = b[3:2];
      default:
        \65  = a;
    endcase
  endfunction
  assign _08_ = \65 (_62_, 4'h1, { _07_, _06_ });
  assign _09_ = OPCODE == 7'h63;
  assign _10_ = OPCODE == 7'h03;
  assign _12_ = OPCODE == 7'h23;
  assign _13_ = FUNCT3 == 3'h5;
  assign _14_ = _13_ ? { FUNCT7[3], FUNCT3 } : { 1'h0, FUNCT3 };
  assign _15_ = OPCODE == 7'h13;
  assign _16_ = OPCODE == 7'h33;
  assign _17_ = OPCODE == 7'h0f;
  assign _18_ = FUNCT3[2] ? 2'h2 : 2'h0;
  assign _19_ = FUNCT3[2] ? 2'h1 : 2'h2;
  assign PC_Sel = _62_;
  assign A_Sel = _48_;
  assign B_Sel = _49_;
  assign WB_Sel = _50_;
  assign Imm_Sel = _51_;
  assign ALU_Sel = _52_;
  assign RegFile_Wen = _63_;
  assign DMem_Wen = _64_;
  assign CSRFile_Wen = _66_;
  assign CSRFile_Trap_Wen = _67_;
  assign MRet = _68_;
  assign ECall = _69_;
  assign EBreak = _70_;
  assign Ill_op = _71_;
endmodule
